name: JarvisUltimate
options:
  bundleIdPrefix: com.jarvisultimate
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    from: "0.15.0"

targets:
  JarvisUltimate:
    type: application
    platform: macOS
    sources:
      - path: JarvisUltimate
        excludes:
          - "**/*.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jarvisultimate.app
        PRODUCT_NAME: Jarvis Ultimate
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_LSUIElement: true
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Jarvis Ultimate needs microphone access to transcribe your voice."
        CODE_SIGN_ENTITLEMENTS: JarvisUltimate/JarvisUltimate.entitlements
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
    dependencies:
      - package: WhisperKit
    entitlements:
      path: JarvisUltimate/JarvisUltimate.entitlements
